
CREATE TABLE Notes (
    Id SERIAL PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Content TEXT,
    Filed BOOLEAN DEFAULT FALSE,
    DateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DateModification TIMESTAMP
);


CREATE TABLE Categories (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE
);

-- NotaXCategorias
CREATE TABLE NotexCategory (
    NoteId INT NOT NULL,
    CategoryId INT NOT NULL,
    PRIMARY KEY (NoteId, CategoryId),
    FOREIGN KEY (NoteId) REFERENCES Notes(Id) ON DELETE CASCADE,
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE CASCADE
);